FROM snowplow/snowplow-enrich-kinesis:6.10.0
COPY enrich.hocon /snowplow/config/enrich.hocon
COPY iglu-resolver.json /snowplow/config/iglu-resolver.json
COPY enrichments/ /snowplow/config/enrichments/
